main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-item', create_item, name='create_item'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-item-ajax/', add_item_ajax, name='add_item_ajax'),
    path('add_item_amount/<int:item_id>', add_item_amount, name='add_item_amount'),
    path('add_amount_ajax', add_amount_ajax, name='add_amount_ajax'),
    path('dec_item_amount/<int:item_id>', dec_item_amount, name='dec_item_amount'),
    path('dec_amount_ajax', dec_amount_ajax, name='dec_amount_ajax'),
    path('remove_item/<int:item_id>', remove_item, name='remove_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('remove_item_ajax/', remove_item_ajax, name="remove_item_ajax"),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

rpg_inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    power = models.IntegerField()
    price = models.IntegerField()
    amount = models.IntegerField()
    
    CATEGORY_CHOICES = [
        ("Weapons", "Weapons"),
        ("Armors", "Armors"),
        ("Consumables", "Consumables"),
        ("Magic Items", "Magic Items"),
        ("Miscellaneous", "Miscellaneous"),
    ]

    category = models.CharField(max_length=255, choices=CATEGORY_CHOICES)
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "power", "category", "price", "amount" ,"description"]

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseNotFound
from main.forms import ItemForm
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.urls import reverse
from main.models import Item
import datetime
import json

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP C',
        'items' : items,
        'total_item' : items.count,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'form': form,
        'name': request.user.username,
        'class': 'PBP C',  
    }
    return render(request, "create_item.html", context)

def get_item_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':

        name = request.POST.get("name")
        power = request.POST.get("power")
        category = request.POST.get("category")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, power=power, category=category, price=price, amount=amount, description=description, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def add_item_amount(request, item_id):
    item = Item.objects.get(id=item_id, user=request.user)
    item.amount += 1
    item.save()

    return redirect('main:show_main')

@csrf_exempt
def add_amount_ajax(request):
    if request.method == 'PATCH':
        pk = json.loads(request.body).get('pk')
        item = Item.objects.get(pk=pk)
        item.amount += 1
        item.save()
        return HttpResponse(b"ADDED", 201)
    
    return HttpResponseNotFound

def dec_item_amount(request, item_id):
    item = Item.objects.get(id=item_id, user=request.user)
    if (item.amount == 1):
        item.delete()
    else:
        item.amount -= 1
        item.save()
        
    return redirect('main:show_main')

@csrf_exempt
def dec_amount_ajax(request):
    if request.method == 'PATCH':
        pk = json.loads(request.body).get('pk')
        item = Item.objects.get(pk=pk)
        item.amount -= 1
        item.save()
        return HttpResponse(b"ADDED", 201)
    
    return HttpResponseNotFound

def remove_item(request, item_id):
    item = Item.objects.get(id=item_id, user=request.user)
    item.delete()

    return redirect('main:show_main')

@csrf_exempt
def remove_item_ajax(request):
    if request.method == 'DELETE':
        pk = json.loads(request.body).get('pk')
        item = Item.objects.get(pk=pk)
        item.delete()
        return HttpResponse(b"DELETED", 201)
    
    return HttpResponseNotFound()

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            power = int(data["power"]),
            price = int(data["price"]),
            amount = int(data["amount"]),
            description = data["category"],
            description = data["description"],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 
{% load static %}

{% block meta %}
<Style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #fff;
        background-image: linear-gradient(rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.1)),
                            url(https://i.pinimg.com/originals/82/74/72/827472c996956ff73ca44addd4ced98f.png);
        color: #2d2d2d;
        margin: 0;
        padding: 0;
    }

    h1 {
        padding: 20px;
        text-align: center;
        font-weight: bold;
        color: #fff;
    }

    button {
        background-color: #1a3891;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    button:hover {
        background-color: #2959e6;
    }

    nav, .navbar, .container-fluid {
        background-color: #2d2d2d;
    }

    .navbar-brand {
        color: #fff;
    }

    .navbar-nav .nav-link {
        color: #fff;
    }

    .navbar-nav .nav-link.active {
        color: #fff;
    }

    .navbar-toggler-icon {
        background-color: #fff;
    }

    .biodata {
        color: #fff;
    }

    .card {
        width: 500px;
        min-width: 500px;
        padding: 20px;
        border-radius: 20px;
        background-color: rgba(255, 255, 255, 0.3);
        backdrop-filter: blur(10px);
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        display: block;
        margin: 0 auto;
    }

    input {
        min-width: 343px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    input[type="submit"] {
        width: 100px;
        border: none;
        border-radius: 10px;
        background-color: #1a3891;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        color: #fff;
        padding: 10px 20px;
        cursor: pointer;
        text-align: center;
        margin: 5px 5px 5px -35px;
    }

    input[type="submit"]:hover {
        background-color: #2959e6;
    }


    .home-page, .logout {
        width: 140px;
    }

</Style>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">RPG Inventory</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li>
                    <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">
                        <button class="home-page">
                            Home
                        </button>
                    </a>
                </li>
                <li>
                    <a class="bottom-button nav-link active" href="{% url 'main:create_item' %}">
                        <button class="add-new-item">
                            Add New Item
                        </button>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:logout' %}">
                        <button class="logout">
                            Logout
                        </button>
                    </a>
                </li>
            </ul>
            <div class="biodata">
                <h5>Name: {{ name }}</h5>
                <h5>Class: {{ class }}</h5>
            </div>
        </div>
    </div>
</nav>

<h1>Add New Item</h1>

<form class="card" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

<title>RPG Inventory Login</title>
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #fff;
        background-image: linear-gradient(rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.1)),
                            url(https://i.pinimg.com/originals/82/74/72/827472c996956ff73ca44addd4ced98f.png);
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        color: #2d2d2d;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
    }

    h1 {
        padding: 20px;
        text-align: center;
        font-weight: bold;
    }

    .login {
        width: 25%;
        min-width: 400px;
        padding: 20px;
        border-radius: 10px;
        background-color: rgba(255, 255, 255, 0.3);
        backdrop-filter: blur(10px);
        border-radius: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        display: block;
        margin: 0 auto;
    }

    input[type="text"],
    input[type="password"] {
        width: 100%;
        margin-left: 15px;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
        background-color: #fff;
        color: #333;
    }

    .login-form {
        margin: 5px 0 5px 5px;
    }

    .login_btn {
        width: 72%;
        background-color: #1a3891;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        text-align: center;
        margin: 5px 5px 5px 9px;
    }

    .login_btn:hover {
        background-color: #2959e6;
    }

    .no-account {
        text-align: center;
    }
</style>
    
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table class="login-form">
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <p class="no-account">Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>

</div>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

<title>RPG Inventory Register</title>
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #fff;
        background-image: linear-gradient(rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.1)),
                            url(https://i.pinimg.com/originals/82/74/72/827472c996956ff73ca44addd4ced98f.png);
        color: #2d2d2d;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
    }

    .register {
        width: 50%;
        min-width: 400px;
        padding: 20px;
        background-color: rgba(255, 255, 255, 0.3);
        backdrop-filter: blur(10px);
        border-radius: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        display: block;
        margin: 0 auto;
    }

    h1 {
        padding: 20px;
        text-align: center;
        font-weight: bold;
    }

    input[type="text"],
    input[type="password"] {
        width: 100%;
        padding: 10px;
        margin: 5px 0 5px 20px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    input[type="submit"], .login {
        width: 72%;
        background-color: #1a3891;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        text-align: center;
        margin: 5px 5px 5px 5px;
    }

    input[type="submit"]:hover, .login:hover {
        background-color: #2959e6;
    }

    ul {
        display: none;
        list-style: none;
        padding: 0;
    }

    ul li {
        display: none;
        color: red;
        margin-left: 15px;
    }

    .back-to-login {
        margin: 20px 0 20px 189px;
        width:350px;
    }

    .login {
        width: 347px;
        margin: 20px 0 20px 0;
        text-align: center;
    }

    p {
        text-align: center;
        margin-top: 20px;
    }
</style>
    
{% endblock meta %}

{% block content %}  

<div class = "register">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Register"/></td>  
                </tr>  
            </table>
        </form>

        <a class="back-to-login" href="{% url 'main:login' %}">
                <button class="login">
                    Login
                </button>
        </a>

    {% if messages %}  
        <ul class="error-messages">   
            {% for message in messages %}  
                <li class="error-message">{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}